// Generated by https://quicktype.io

export interface Es {
    navigation: Navigation;
    page:       Page;
}

export interface Navigation {
    home:  string;
    about: string;
}

export interface Page {
    home:  About;
    about: About;
}

export interface About {
    title:       string;
    description: string;
}
